linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - varcheck

  disable:
    - gofumpt

  presets:
    - format
    - import

linters-settings:
  govet:
    disable:
        # Unkeyed primitive.E and timestamp fields are used extensively in code taken from
        # mongosync.
        - composites
