on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  basics:
    strategy:
      fail-fast: false
      matrix:
        os:
          - runsOn: macos-latest
            setup: brew install parallel

          - runsOn: ubuntu-latest

        version:
          - '4.2'
          - '4.4'
          - '5.0'
          - '6.0'
          - '7.0'
          - '8.0'

        topology:
          - name: replset
            srcConnStr: mongodb://localhost:27020,localhost:27021,localhost:27022
            dstConnStr: mongodb://localhost:27030,localhost:27031,localhost:27032

          - name: sharded
            args: --sharded 2
            srcConnStr: mongodb://localhost:27020
            dstConnStr: mongodb://localhost:27030

    runs-on: ${{matrix.os.runsOn}}

    steps:
      - name: Install packages
        run: ${{ matrix.os.setup }}

      - name: Install m
        run: npm install -g m mongosh

      - name: Activate MongoDB ${{ matrix.version }}
        run: yes | m ${{ matrix.version }}

      - name: Install mtools
        run: pipx install 'mtools[all]'

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Fetch Go ${{ matrix.go_version }}
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build
        run: go build main/migration_verifier.go

      - name: Start clusters
        run: |-
            {
                echo "mlaunch init --port 27020 --dir src --replicaset ${{ matrix.topology.args }}"
                echo "mlaunch init --port 27030 --dir dst --replicaset ${{ matrix.topology.args }}"
                echo "mlaunch init --port 27040 --dir meta --replicaset --nodes 1"
            } | parallel

      - name: Test
        run: go test -v ./...
        env:
          MVTEST_SRC: ${{matrix.topology.srcConnStr}}
          MVTEST_DST: ${{matrix.topology.dstConnStr}}
          MVTEST_META: mongodb://localhost:27040
          MVTEST_TOPOLOGY: ${{matrix.topology.name}}
