on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  basics:
    strategy:
      fail-fast: false
      matrix:
        os:
          - runsOn: macos-latest
            setup: brew install pip3

          - runsOn: ubuntu-latest
            setup: apt install -y pip3

        version:
          - '4.2'
          - '4.4'
          - '5.0'
          - '6.0'
          - '7.0'
          - '8.0'

        topology:
          - name: replset
            args: --replicaset --nodes 1

          - name: sharded
            args: --sharded 2 --nodes 1

        go_version:

          # This is hard-coded by design in order to catch inadvertent changes
          # to the minimum-required Go version to build migration-verifier.
          - '1.20'
          - stable

    runs-on: ${{matrix.os.runsOn}}

    steps:
       - run: echo ${{matrix.os.runsOn}}
#    runs-on: ${{matrix.os.runsOn}}
#
#    steps:
#      - name: Install m
#        run: npm install -g m
#
#      - name: Activate MongoDB ${{ matrix.version }}
#        run: m activate ${{ matrix.version }}
#
#      - name: Install mtools
#        run: pip3 install 'mtools[all]'
#
#      - name: Start source cluster
#        run: mlaunch init --port 27020 ${{ matrix.topology.args }}
#
#      - name: Start destination cluster
#        run: mlaunch init --port 27030 ${{ matrix.topology.args }}
#
#      - name: Start metadata cluster
#        run: mlaunch init --port 27040 ${{ matrix.topology.args }}
#
#      - name: Check out repository
#        uses: actions/checkout@v4
#
#      - name: Fetch Go ${{ matrix.go_version }}
#        uses: actions/setup-go@v5
#        with:
#          go-version: ${{ matrix.go_version }}
#
#      - name: Build
#        run: go build main/migration_verifier.go
#
#      - name: Test
#        run: go test -v ./...
#        env:
#          MVTEST_SRC: localhost:27020
#          MVTEST_DST: localhost:27030
#          MVTEST_META: localhost:27040
