on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  basics:
    strategy:
      fail-fast: false
      matrix:
        os:
          - runsOn: macos-latest
            setup: brew install parallel

          - runsOn: ubuntu-latest

        version:
          - '4.2'
          - '4.4'
          - '5.0'
          - '6.0'
          - '7.0'
          - '8.0'

        topology:
          - name: replset
            srcConnStr: mongodb://127.0.0.1:27020,127.0.0.1:27021,127.0.0.1:27022
            dstConnStr: mongodb://127.0.0.1:27030,127.0.0.1:27031,127.0.0.1:27032
            metaConnStr: mongodb://127.0.0.1:27040,127.0.0.1:27041,127.0.0.1:27042

#          - name: sharded
#            args: --sharded 2
#            srcConnStr: mongodb://127.0.0.1:27020
#            dstConnStr: mongodb://127.0.0.1:27030
#            metaConnStr: mongodb://127.0.0.1:27040

        go_version:

          # This is hard-coded by design in order to catch inadvertent changes
          # to the minimum-required Go version to build migration-verifier.
#          - '1.20'
          - stable

    runs-on: ${{matrix.os.runsOn}}

    steps:
      - name: Install packages
        run: ${{ matrix.os.setup }}

      - name: Install m
        run: npm install -g m mongosh

      - name: Activate MongoDB ${{ matrix.version }}
        run: yes | m ${{ matrix.version }}

      - name: Install mtools
        run: pipx install 'mtools[all]'

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Fetch Go ${{ matrix.go_version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}

      - name: Build
        run: go build main/migration_verifier.go

      - name: Start clusters
        run: |-
            {
                echo "mlaunch init --port 27020 --dir src --replicaset ${{ matrix.topology.args }}"
                echo "mlaunch init --port 27030 --dir dst --replicaset ${{ matrix.topology.args }}"
                echo "mlaunch init --port 27040 --dir meta --replicaset ${{ matrix.topology.args }}"
            } | parallel

#      - run: mlaunch init --port 27020 --dir src --replicaset ${{ matrix.topology.args }}
#      - run: mlaunch init --port 27030 --dir dst --replicaset ${{ matrix.topology.args }}
#      - run: mlaunch init --port 27040 --dir meta --replicaset ${{ matrix.topology.args }}

      - name: Await source readiness
        run: while true; do mongosh "${{ matrix.topology.srcConnStr }}" --eval 'db.hello()' && break; sleep 1; done



      - name: Test
        run: go test -v ./...
        env:
          MVTEST_SRC: ${{matrix.topology.srcConnStr}}
          MVTEST_DST: ${{matrix.topology.dstConnStr}}
          MVTEST_META: ${{matrix.topology.metaConnStr}}
        continue-on-error: true

      - run: ls -la src
