on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  basics:
    strategy:
      fail-fast: false
      matrix:
        os:
          - runsOn: macos-latest
            setup: brew install pipx parallel

          - runsOn: ubuntu-latest
            setup: apt install -y pipx parallel

        version:
          - '4.2'
          - '4.4'
          - '5.0'
          - '6.0'
          - '7.0'
          - '8.0'

        topology:
          - name: replset

          - name: sharded
            args: --sharded 2

        go_version:

          # This is hard-coded by design in order to catch inadvertent changes
          # to the minimum-required Go version to build migration-verifier.
          - '1.20'
          - stable

    runs-on: ${{matrix.os.runsOn}}

    steps:
      - name: Install m
        run: npm install -g m

      - name: Activate MongoDB ${{ matrix.version }}
        run: yes | m ${{ matrix.version }}

      - name: Install mtools
        run: pipx install 'mtools[all]'

      - name: Start clusters
        run: |-
            {
                echo "mlaunch init --port 27020 --dir src --replicaset ${{ matrix.topology.args }}"
                echo "mlaunch init --port 27030 --dir dst --replicaset ${{ matrix.topology.args }}"
                echo "mlaunch init --port 27040 --dir meta --replicaset ${{ matrix.topology.args }}"
            } | parallel

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Fetch Go ${{ matrix.go_version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}

      - name: Build
        run: go build main/migration_verifier.go

      - name: Test
        run: go test -v ./...
        env:
          MVTEST_SRC: mongodb://localhost:27020
          MVTEST_DST: mongodb://localhost:27030
          MVTEST_META: mongodb://localhost:27040
